### ISSUE TITLE
inline_link_clicks returns 0 when filtering on action_type

### ISSUE THREAD

**Issue by fredericharnois** [fredericharnois/facebook-ads-reporting-google-apps-script#1]
`&filtering[{"field":"action_type","operator":"CONTAIN","value":"offsite_conversion.fb_pixel_purchase"}]`
is causing inline_link_clicks to return 0.

[This seems to be a bug](https://developers.facebook.com/support/bugs/182593865733037/) in Facebook's Ad Insights API.

**Comment by fredericharnois** [comment]
Filed a [bug report](https://developers.facebook.com/support/bugs/233775843881530/) directly with Facebook since the issue persists.

**Comment by fredericharnois** [comment]
According to Facebook, this filtering behaviour is by design. Modified the script so that both inline_link_clicks and offsite_conversion.fb_pixel_purchase values are included in the report.

**Comment by DigitalLoz** [comment]
your query 
&filtering[{"field":"action_type","operator":"CONTAIN","value":"offsite_conversion.fb_pixel_purchase"}]

seems to be missing the = after filtering

&filtering**=**[{"field":"action_type","operator":"CONTAIN","value":"offsite_conversion.fb_pixel_purchase"}]
