### ISSUE TITLE
export-report in local language

### ISSUE THREAD

**Issue by lsp1138** [fredericharnois/facebook-ads-reporting-google-apps-script#13]
Hello Frederic, thank you for putting this together. I am at the cross roads between parsing the JSON and using the export-report provided by Facebook. I need a few of the actions/conversions and also using all the attribution windows options so its a bit fickle to set up the object parsing and the all encompassing report from Facebook is attractive. However since I am currently in Spain the CSV output comes in Spanish. I have been searching for a way to force it to output in English as I don't want the report to change depending on where in the world I am at.. any idea of how to do that? 

Otherwise I will go ahead and parse the JSON (I do it Ad by Ad and with a daily reporting).

regards,
Lars

**Comment by flescobarp** [comment]
> Hello Frederic, thank you for putting this together. I am at the cross roads between parsing the JSON and using the export-report provided by Facebook. I need a few of the actions/conversions and also using all the attribution windows options so its a bit fickle to set up the object parsing and the all encompassing report from Facebook is attractive. However since I am currently in Spain the CSV output comes in Spanish. I have been searching for a way to force it to output in English as I don't want the report to change depending on where in the world I am at.. any idea of how to do that?
> 
> Otherwise I will go ahead and parse the JSON (I do it Ad by Ad and with a daily reporting).
> 
> regards,
> Lars

Hi!, to force the output in English, in the _getFacebookReport()_ function, add _&locale=en_US_ at the end of the _url_ constant, something like this:

_const url = `` `https://www.facebook.com/ads/ads_insights/export_report?report_run_id=${reportId}&format=csv&access_token=${TOKEN}&locale=en_US` ``;_

**Comment by lsp1138** [comment]
Thank you so much for the quick response Frederic, this worked perfectly. Lars
