### ISSUE TITLE
Facebook ads leads to spreadsheet

### ISSUE THREAD

**Issue by orelmeister** [fredericharnois/facebook-ads-reporting-google-apps-script#3]
will this process allows me to retrieve the facebook leads to a google spreadsheet? if not, what changes do i need to make?

**Comment by fredericharnois** [comment]
Hello @orelmeister!

This script will export a report with the number of leads that an ad, adset, campaign or account brought in, but not the lead form informations.

Here's the [documentation](https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving) to get an export of your leads.

That being said, I would be open to building a script that handles that export if you're willing to test it (I don't currently have access to an account that runs lead gen ads).

Let me know if you'd be interested.

**Comment by orelmeister** [comment]
Hi,
Thanks for the fast reply!
If you can build a script to extract leads to a google spreadsheet I would
definitely test it out

**Comment by fredericharnois** [comment]
Hi @orelmeister,

No problem!

Here's the [repository](https://github.com/fredericharnois/facebook-leads-reporting-google-apps-script) for the new script.

Let me know if you encounter any issues there.

Thanks!
