### ISSUE TITLE
Request failed for https://www.facebook.com/ads/ads_insights/export_report?

### ISSUE THREAD

**Issue by eblakeway1990** [fredericharnois/facebook-ads-reporting-google-apps-script#5]
Hello!

Apologies as I am relatively new to this but I am getting the following error:

Request failed for https://www.facebook.com/ads/ads_insights/export_report?

I also have the two scripts all in one project, is that correct? What is the best way to have one to fire after the other?

My script is below but i have removed the token for security:

/**
*
* Export Facebook Ads Data to Google Sheets
* 
* Requests a Facebook report asynchronously and caches the report ID
*
* Version: 2.1
* Google Apps Script maintained by Frederic Harnois
*
**/

// MODIFY YOUR REPORT HERE //

// ad account ID
var AD_ACCOUNT_ID = 'xxx'

// ad, adset, campaign, account
var LEVEL = 'ad'

// https://developers.facebook.com/docs/marketing-api/insights/parameters#fields
var FIELDS = 'ad_name'

// https://developers.facebook.com/docs/marketing-api/insights/parameters#param
var DATE_RANGE = 'last_90d'

// user access token linked to a Facebook app
var TOKEN = 'xxx'

// number of days from 1 to 90
var TIME_INCREMENT = 'all_days'

// https://developers.facebook.com/docs/marketing-api/insights/parameters#param
var FILTERING = 'Array'

// DO NOT MODIFY ANYTHING BELOW //

function requestFacebookReport() {

  // Builds the Facebook Ads Insights API URL
  var facebookUrl = 
    'https://graph.facebook.com/v3.3' + 
    '/act_' + AD_ACCOUNT_ID +
    '/insights?level=' + LEVEL +
    '&fields=' + FIELDS +
    '&date_preset=' + DATE_RANGE +
    '&access_token=' + TOKEN +
    '&time_increment=' + TIME_INCREMENT +
    '&filtering=' + FILTERING +
    '&limit=1000';
  var encodedFacebookUrl = encodeURI(facebookUrl);
  var options = {
    'method' : 'post'
  };
  
  // Fetches & parses the URL 
  var fetchRequest = UrlFetchApp.fetch(encodedFacebookUrl, options);
  var results = JSON.parse(fetchRequest.getContentText());
  
  // Caches the report run ID
  var reportId = results.report_run_id;
  var cache = CacheService.getScriptCache();
  var cached = cache.get("campaign-report-id");
  
  if (cached != null) {
    cache.put("campaign-report-id", [], 1);
    Utilities.sleep(1001);
    cache.put("campaign-report-id", reportId, 21600);
    }
  else {
    cache.put("campaign-report-id", reportId, 21600); 
    }
  Logger.log(cache.get('campaign-report-id'));
}/**
*
* Export Facebook Ads Data to Google Sheets
* 
* Pushes the Facebook asynchronous report to Google Sheets
*
* Version: 2.1
* Google Apps Script maintained by Frederic Harnois
*
**/

// MODIFY YOUR SETTINGS HERE //

// url of the google sheets where the report will be
var SPREADSHEET_URL = 'xxx'

// name of the sheet where the report will be
var TAB_NAME = 'report'

// user access token linked to a Facebook app
var TOKEN = xxx

// DO NOT MODIFY ANYTHING BELOW //

function getfacebookReport() {
  
  // Selects the chosen sheet and tab
  var ss = SpreadsheetApp.openByUrl(SPREADSHEET_URL);
  var sheet = ss.getSheetByName(TAB_NAME);
  
  // Clears the sheet
  sheet.clear();
  
  // Gets the Facebook report run ID
  var cache = CacheService.getScriptCache();
  var reportId = cache.get('campaign-report-id')

  // Fetches the report as a csv file
  var url = 
      'https://www.facebook.com/ads/ads_insights/export_report' +
      '?report_run_id=' + reportId +
      '&format=csv' +
      '&access_token=' + TOKEN;
  var fetchRequest = UrlFetchApp.fetch(url);
  var results = Utilities.parseCsv(fetchRequest);
  
  // Pastes the csv file in the sheet
  sheet.getRange(1,1, results.length, results[0].length).setValues(results);
}

**Comment by fredericharnois** [comment]
Hi @eblakeway1990!

I usually set both scripts in the same projects but in different script files for clarity.

In order to fire requestFacebookReport before getfacebookReport, I set the daily trigger for requestFacebookReport one hour before getfacebookReport (Edit > Current project's triggers).

As far as your error, it looks like reportId isn't getting passed from requestFacebookReport to getfacebookReport. When you run requestFacebookReport, do you see the id in the logs (View > Logs)?

**Comment by eblakeway1990** [comment]
Thanks for this. All sorted now although I seem to be getting a parsing error when the script loads. It's off because it worked a few times but now seems to fail at the final hurdle. I tried reducing to last_7d to reduce the amount of data to parse but didn't work. I also tested the URL and opened the file but nothing too unusual. Any tips on how to get round parsing errors would be welcome.

Thanks again for this, great script for me to get my teeth into

**Comment by fredericharnois** [comment]
Glad I can help! Can you please tell me more about the parsing error (error message/screenshots)?

**Comment by eblakeway1990** [comment]
I think I have sorted it now, it was because I put one script under the other and had variables called the same thing causing some confusion. It's all working now! 

One thing I was keen to do was reference a cell for the token and account ID rather than have it hard coded. Any idea how to do this?

**Comment by fredericharnois** [comment]
That's great!

And sure, you'll first want to remove these variables from the settings part of both scripts:

```
// ad account ID
var AD_ACCOUNT_ID = 'xxx'
```

```
// user access token linked to a Facebook app
var TOKEN = 'xxx'
```

Now, let's say for the sake of this example that the tab where you have your token and accound ID is called "Settings" and that they're respectively in cells A1 and A2.

You'll want to add this to **request-facebook-report**:

```
 function requestFacebookReport() {

  // ADD THE FOUR LINES BELOW
  var ss = SpreadsheetApp.openByUrl(SPREADSHEET_URL);
  var settings = ss.getSheetByName("Settings");
  var TOKEN = settings.getRange("A1").getValue();
  var AD_ACCOUNT_ID = settings.getRange("A2").getValue();	

  // Builds the Facebook Ads Insights API URL
  var facebookUrl = ...
```

You'll also want to make sure SPREADSHEET_URL is defined somewhere.

For **get-facebook-report**, you'll want to add this:

```
function getFacebookReport() {
  
  // Selects the chosen sheet and tab
  var ss = SpreadsheetApp.openByUrl(SPREADSHEET_URL);
  var sheet = ss.getSheetByName(TAB_NAME);

  // ADD THE TWO LINES BELOW
  var settings = ss.getSheetByName("Settings");
  var TOKEN = settings.getRange("A1").getValue();

  // Clears the sheet
  sheet.clear();
```

Let me know if you've got issues regarding this or any other questions!
