### ISSUE TITLE
{"error":{"message":"(#100)  param filtering must be an array."

### ISSUE THREAD

**Issue by deepakshantilalshah** [fredericharnois/facebook-ads-reporting-google-apps-script#6]
Hi, 

I am using the below format in for filtering (in request-facebook script). 

`var FILTERING = [{"field":"action_type","operator":"IN","value":["link_click"]}]`

And it returns the following error:

> Request failed for https://graph.facebook.com returned code 400. Truncated server response: {"error":{"message":"(#100) param filtering must be an array.","type":"OAuthException","code":100,"fbtrace_id":"xx"}} (use muteHttpExceptions option to examine full response) (line 59, file "request-facebook-report.js")

Should I put this in some other format?

**Comment by fredericharnois** [comment]
Hi @deepakshantilalshah!

Can you try this and let me know if it works?

`var FILTERING = "[{'field':'action_type','operator':'IN','value':['link_click']}]"`

Thanks!

**Comment by Suleman-Elahi** [comment]
It works !!!

Thanks @fredericharnois 

![image](https://user-images.githubusercontent.com/24384996/69337383-bcbee700-0c86-11ea-9b83-71cf956249df.png)

**Comment by prakash-jayaswal-au6** [comment]
> "[{'field':'action_type','operator':'IN','value':['link_click']}]"

sorry but this not work for me , in https://graph.facebook.com for catalog with request, can u suggest otheres

**Comment by igchernin** [comment]
is it possible to somehow filter by 2 parameters?
