### ISSUE TITLE
Cannot get conversions

### ISSUE THREAD

**Issue by sinapsmarketing** [fredericharnois/facebook-ads-reporting-google-apps-script#7]
Hello

The conversions field appears like it's ignored, no  data comes for that column.
Can conversions be pulled from the graph api / reporting ?

I'm using this:
```
var LEVEL = 'campaign'
var FIELDS = "['account_id','account_name','campaign_name','impressions','inline_link_clicks',
'website_ctr','cpc','conversions','conversion_values','cost_per_conversion','spend']"
var DATE_RANGE = 'last_month'
```

**Comment by scott-coates** [comment]
I'm running into this as well. What's the proper way to get # of conversions?

**Comment by sinapsmarketing** [comment]
I don't remember exactly what the problem was, I think the last version of fields that worked was this:
var FIELDS = "['account_id','account_name','campaign_name','impressions','inline_link_clicks','website_ctr','cpc','conversions','conversion_values','cost_per_conversion','spend','actions']"

I'm not using this script anymore because it gives random errors very often. The errors come either from Google Apps limitations and general weird behaviour or because FB fails to deliver the report in time and google just won't wait for it. 
I used the logic from this script and made a php script where I have more control. Hope it helps
